// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SDMBackend.DAL;

#nullable disable

namespace SDMBackend.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260128191103_SeedAdminFixed")]
    partial class SeedAdminFixed
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SDMBackend.Models.Dependency", b =>
                {
                    b.Property<int>("DependencyID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DependencyID"));

                    b.Property<int>("DependsOnModuleID")
                        .HasColumnType("int");

                    b.Property<int>("ModuleID")
                        .HasColumnType("int");

                    b.HasKey("DependencyID");

                    b.HasIndex("ModuleID");

                    b.ToTable("Dependencies");
                });

            modelBuilder.Entity("SDMBackend.Models.Developer", b =>
                {
                    b.Property<int>("DeveloperID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DeveloperID"));

                    b.Property<int>("Experience")
                        .HasColumnType("int");

                    b.Property<int>("UserID")
                        .HasColumnType("int");

                    b.HasKey("DeveloperID");

                    b.HasIndex("UserID")
                        .IsUnique();

                    b.ToTable("Developers");
                });

            modelBuilder.Entity("SDMBackend.Models.Module", b =>
                {
                    b.Property<int>("ModuleID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ModuleID"));

                    b.Property<string>("ModuleName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ProjectID")
                        .HasColumnType("int");

                    b.Property<string>("Version")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ModuleID");

                    b.HasIndex("ProjectID");

                    b.ToTable("Modules");
                });

            modelBuilder.Entity("SDMBackend.Models.ModuleTechnology", b =>
                {
                    b.Property<int>("ModuleID")
                        .HasColumnType("int");

                    b.Property<int>("TechID")
                        .HasColumnType("int");

                    b.Property<int?>("TechnologyTechID")
                        .HasColumnType("int");

                    b.HasKey("ModuleID", "TechID");

                    b.HasIndex("TechnologyTechID");

                    b.ToTable("ModuleTechnologies");
                });

            modelBuilder.Entity("SDMBackend.Models.Project", b =>
                {
                    b.Property<int>("ProjectID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProjectID"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ProjectName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ProjectID");

                    b.ToTable("Projects");
                });

            modelBuilder.Entity("SDMBackend.Models.TaskEntity", b =>
                {
                    b.Property<int>("TaskID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TaskID"));

                    b.Property<int>("DeveloperID")
                        .HasColumnType("int");

                    b.Property<int>("ModuleID")
                        .HasColumnType("int");

                    b.Property<string>("Priority")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TaskName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("TaskID");

                    b.HasIndex("DeveloperID");

                    b.HasIndex("ModuleID");

                    b.ToTable("Tasks");
                });

            modelBuilder.Entity("SDMBackend.Models.Technology", b =>
                {
                    b.Property<int>("TechID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TechID"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TechName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("TechID");

                    b.ToTable("Technologies");
                });

            modelBuilder.Entity("SDMBackend.Models.User", b =>
                {
                    b.Property<int>("UserID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserID"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserID");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            UserID = 1,
                            Email = "admin@example.com",
                            Name = "Admin",
                            PasswordHash = "$2a$11$E0u0lYH8A0e7hA1vQoKJTe9lH90Oy6J5XK6Vb3CMhYvgn5rXzEoG.",
                            Role = "Admin"
                        });
                });

            modelBuilder.Entity("SDMBackend.Models.Dependency", b =>
                {
                    b.HasOne("SDMBackend.Models.Module", "Module")
                        .WithMany("Dependencies")
                        .HasForeignKey("ModuleID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Module");
                });

            modelBuilder.Entity("SDMBackend.Models.Developer", b =>
                {
                    b.HasOne("SDMBackend.Models.User", "User")
                        .WithOne("Developer")
                        .HasForeignKey("SDMBackend.Models.Developer", "UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("SDMBackend.Models.Module", b =>
                {
                    b.HasOne("SDMBackend.Models.Project", "Project")
                        .WithMany("Modules")
                        .HasForeignKey("ProjectID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Project");
                });

            modelBuilder.Entity("SDMBackend.Models.ModuleTechnology", b =>
                {
                    b.HasOne("SDMBackend.Models.Module", "Module")
                        .WithMany("ModuleTechnologies")
                        .HasForeignKey("ModuleID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SDMBackend.Models.Technology", "Technology")
                        .WithMany("ModuleTechnologies")
                        .HasForeignKey("TechnologyTechID");

                    b.Navigation("Module");

                    b.Navigation("Technology");
                });

            modelBuilder.Entity("SDMBackend.Models.TaskEntity", b =>
                {
                    b.HasOne("SDMBackend.Models.Developer", "Developer")
                        .WithMany()
                        .HasForeignKey("DeveloperID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SDMBackend.Models.Module", "Module")
                        .WithMany("Tasks")
                        .HasForeignKey("ModuleID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Developer");

                    b.Navigation("Module");
                });

            modelBuilder.Entity("SDMBackend.Models.Module", b =>
                {
                    b.Navigation("Dependencies");

                    b.Navigation("ModuleTechnologies");

                    b.Navigation("Tasks");
                });

            modelBuilder.Entity("SDMBackend.Models.Project", b =>
                {
                    b.Navigation("Modules");
                });

            modelBuilder.Entity("SDMBackend.Models.Technology", b =>
                {
                    b.Navigation("ModuleTechnologies");
                });

            modelBuilder.Entity("SDMBackend.Models.User", b =>
                {
                    b.Navigation("Developer");
                });
#pragma warning restore 612, 618
        }
    }
}
